### PR TITLE
Color changes

### PR DESCRIPTION
**Pull request by aappling-usgs**
Mainly adjusting colors of water bodies, with a grey-green for marshes. Also lightened the storm track - what do you think?
gif_frame_a_20170825_00

### CODE REVIEW

**Comment by aappling-usgs** [comment]
@lindsaycarr To use these changes in Gordon, you'll need to add these lines to your viz_config.yml:
```
major_river_col: "#1874cd"
gage_river_col: "#5d9ddc"
lake_col: "#a2c7eb"
marsh_col: "#afd0c7"
ocean_col: "#e7f1fa"
storm_line_col: "grey70"
```

**Comment by lindsaycarr** [comment]
I'm kind of wondering if it's too close to the precip 8-12 or 12-16 categories

**Comment by aappling-usgs** [comment]
The marsh green? Me too, but unless we go for something glaringly bright, I haven't been able to find a color that would do better while still being a little greenish. Another option would be to mess with the precip color scale... I also looked into a pattern fill, ideally something like this:
image
or simpler, but I haven't been able to figure out how to do any sort of pattern yet, especially with sf plotting...

**Comment by aappling-usgs** [comment]
Maybe something grayer?

gif_frame_a_20170825_00

**Comment by lindsaycarr** [comment]
I think the greyer bit is nicer. Overall I like this scheme, I just think we should be open to changing the color when we see it in full majesty once a completed gif is shown

**Comment by aappling-usgs** [comment]
OK, let's do it. You can experiment with different colors by editing the storm-specific viz_config.yml anyway.

**Pull request merged**
