### PR TITLE
initial project skeleton

### PR DESCRIPTION
**Pull request by jzwart**
placeholder txt files should be deleted in subfolders once scripts / data are in

### CODE REVIEW

**Comment by aappling-usgs** [comment]
resolves #14, resolves #8

**Comment by jzwart** [comment]
Yup will add. And I couldn't assign a reviewer - I don't think I have maintenance access to the repo

**Comment by aappling-usgs** [comment]
oh, rats, sorry. could you try assigning a reviewer now?

**Comment by jzwart** [comment]
works now!

**Pull request merged**
