### PR TITLE
draft - Henri 2021

### PR DESCRIPTION
**Pull request by collnell**
Currently stuck on `fetch_river_geometry` due to ended support for the `https://cida.usgs.gov/nwc/geoserver/nhdplus/ows` endpoint

### CODE REVIEW

**Comment by jread-usgs** [comment]
@dblodgett-usgs 
I thought we had a geoserver migration or workaround for this - are you aware?
This is for Hurricane Henri

**Comment by collnell** [comment]
Can get past that by using `nhdplusTools` to pull in flowlines and waterbodies for the base map (https://github.com/USGS-VIZLAB/vizstorm-GIF/pull/238/commits/4bd309a21050592e931473800d69e8dff9a86cb2).

**Comment by collnell** [comment]
Now onto an error coming from `process_precip_rasters()` in `2_process/src/process_precip` 
image

**Comment by collnell** [comment]
I get the following error when running `scmake('6_visualize/tmp/gif_frame_a_20210821_06.png', '6_storm_gif_tasks.yml')`

image

The error occurs when `create_animation_frame` attempts to plot the precip rasters.

**Comment by lindsayplatt** [comment]
That error is usually related to either character data when it should be numeric or completely empty data being passed in. Let's hop on a call and troubleshoot

**Review by lindsayplatt — APPROVED** [review]
We will need to revisit the stuff related to nhdplustools rivers, the `sp` stencil change, the addition of `remake_file = getOption()`, and the changes to precip processing and add to the main branch

**Pull request merged**
